spring:
  application:
    name: NU-Backend

  datasource:
    url: ${DATABASE_URL:jdbc:h2:mem:nudb;MODE=PostgreSQL;DB_CLOSE_DELAY=-1}
    username: ${DATABASE_USER:sa}
    password: ${DATABASE_PASSWORD:}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:

    open-in-view: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8081
